version: "3.7"

services:
  test:
    container_name: gobcore
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "./test.sh"
  python_310:
    container_name: gobcore_py310
    build:
      context: .
      dockerfile: Dockerfile.3.10-slim-bullseye
    command: >
      bash -c "./test.sh"
